// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.24.0";

// src/lib/mcp/tools/list-videos.ts
import { createClient } from "npm:@supabase/supabase-js@^2.99.1";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z } from "npm:zod@^4.4.3";
function supabaseForUser(ctx) {
  return createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_videos_default = defineTool({
  name: "list_videos",
  title: "List videos",
  description: "List videos on VidTube. Optionally filter to the signed-in user's own videos.",
  inputSchema: {
    limit: z.number().int().min(1).max(50).default(10).describe("Max number of videos to return."),
    mine_only: z.boolean().default(false).describe("If true, return only the signed-in user's videos.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit, mine_only }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const sb = supabaseForUser(ctx);
    let query = sb.from("videos").select("id, title, description, views, likes, created_at, user_id").order("created_at", { ascending: false }).limit(limit);
    if (mine_only) query = query.eq("user_id", ctx.getUserId());
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { videos: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-video.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.99.1";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z2 } from "npm:zod@^4.4.3";
function supabaseForUser2(ctx) {
  return createClient2(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var get_video_default = defineTool2({
  name: "get_video",
  title: "Get video",
  description: "Fetch details of a single VidTube video by its ID, including comments.",
  inputSchema: {
    video_id: z2.string().uuid().describe("The UUID of the video.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ video_id }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const sb = supabaseForUser2(ctx);
    const [{ data: video, error: vErr }, { data: comments }] = await Promise.all([
      sb.from("videos").select("*").eq("id", video_id).maybeSingle(),
      sb.from("comments").select("id, content, user_id, created_at").eq("video_id", video_id).order("created_at", { ascending: false }).limit(20)
    ]);
    if (vErr) return { content: [{ type: "text", text: vErr.message }], isError: true };
    if (!video) return { content: [{ type: "text", text: "Video not found" }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify({ video, comments }) }],
      structuredContent: { video, comments: comments ?? [] }
    };
  }
});

// src/lib/mcp/tools/post-comment.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.99.1";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z3 } from "npm:zod@^4.4.3";
function supabaseForUser3(ctx) {
  return createClient3(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var post_comment_default = defineTool3({
  name: "post_comment",
  title: "Post comment",
  description: "Post a comment on a VidTube video as the signed-in user.",
  inputSchema: {
    video_id: z3.string().uuid().describe("UUID of the video to comment on."),
    content: z3.string().trim().min(1).max(2e3).describe("Comment text.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async ({ video_id, content }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const sb = supabaseForUser3(ctx);
    const { data, error } = await sb.from("comments").insert({ video_id, content, user_id: ctx.getUserId() }).select().single();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: `Comment posted (id: ${data.id})` }],
      structuredContent: { comment: data }
    };
  }
});

// src/lib/mcp/tools/my-profile.ts
import { createClient as createClient4 } from "npm:@supabase/supabase-js@^2.99.1";
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.24.0";
function supabaseForUser4(ctx) {
  return createClient4(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var my_profile_default = defineTool4({
  name: "my_profile",
  title: "My profile",
  description: "Get the signed-in user's VidTube profile (username, avatar, bio).",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const sb = supabaseForUser4(ctx);
    const { data, error } = await sb.from("profiles").select("*").eq("user_id", ctx.getUserId()).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify({ profile: data, email: ctx.getUserEmail() }) }],
      structuredContent: { profile: data, email: ctx.getUserEmail() }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "sdrdnvatefhfncusriml";
var mcp_default = defineMcp({
  name: "vidtube-mcp",
  title: "VidTube MCP",
  version: "0.1.0",
  instructions: "Tools for VidTube \u2014 a video platform. Use list_videos and get_video to browse content, post_comment to comment as the signed-in user, and my_profile for the current account.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_videos_default, get_video_default, post_comment_default, my_profile_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.24.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
